### ISSUE TITLE
The command [/bin/sh -c apt-get update] returned a non-zero code: 100

### ISSUE THREAD

**Issue by ghost** [jezdez/dokku-memcached-plugin#1]
I have dokku v0.2.3 running on ubuntu 14.04 (the image from digital ocean)

After installing the link and memcache plugin, I get this error on running dokku plugins-install:
The command [/bin/sh -c apt-get update] returned a non-zero code: 100

> dokku plugins
> /var/lib/dokku/plugins/00_dokku-standard/
> /var/lib/dokku/plugins/backup/
> /var/lib/dokku/plugins/config/
> /var/lib/dokku/plugins/git/
> /var/lib/dokku/plugins/link/
> /var/lib/dokku/plugins/memcached/
> /var/lib/dokku/plugins/nginx-vhosts/

I'm running this as root.
Just running apt-get update works fine.

**Comment by rpontes** [comment]
+1 Same error.

**Comment by ghost** [comment]
This fork seems to work:
https://github.com/jlachowski/dokku-memcached-plugin

**Comment by hakunin** [comment]
+1 same error

**Comment by jezdez** [comment]
Merged that fork into this repo.
